/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EquipamentosRouteImport } from './routes/equipamentos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EquipamentosSlugRouteImport } from './routes/equipamentos.$slug'

const EquipamentosRoute = EquipamentosRouteImport.update({
  id: '/equipamentos',
  path: '/equipamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipamentosSlugRoute = EquipamentosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EquipamentosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/equipamentos': typeof EquipamentosRouteWithChildren
  '/equipamentos/$slug': typeof EquipamentosSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/equipamentos': typeof EquipamentosRouteWithChildren
  '/equipamentos/$slug': typeof EquipamentosSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/equipamentos': typeof EquipamentosRouteWithChildren
  '/equipamentos/$slug': typeof EquipamentosSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/equipamentos' | '/equipamentos/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/equipamentos' | '/equipamentos/$slug'
  id: '__root__' | '/' | '/equipamentos' | '/equipamentos/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EquipamentosRoute: typeof EquipamentosRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/equipamentos': {
      id: '/equipamentos'
      path: '/equipamentos'
      fullPath: '/equipamentos'
      preLoaderRoute: typeof EquipamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipamentos/$slug': {
      id: '/equipamentos/$slug'
      path: '/$slug'
      fullPath: '/equipamentos/$slug'
      preLoaderRoute: typeof EquipamentosSlugRouteImport
      parentRoute: typeof EquipamentosRoute
    }
  }
}

interface EquipamentosRouteChildren {
  EquipamentosSlugRoute: typeof EquipamentosSlugRoute
}

const EquipamentosRouteChildren: EquipamentosRouteChildren = {
  EquipamentosSlugRoute: EquipamentosSlugRoute,
}

const EquipamentosRouteWithChildren = EquipamentosRoute._addFileChildren(
  EquipamentosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EquipamentosRoute: EquipamentosRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
