/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EquipamentosRouteImport } from './routes/equipamentos'
import { Route as EmpresasRouteImport } from './routes/empresas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EquipamentosSlugRouteImport } from './routes/equipamentos.$slug'
import { Route as EmpresasSlugRouteImport } from './routes/empresas.$slug'

const EquipamentosRoute = EquipamentosRouteImport.update({
  id: '/equipamentos',
  path: '/equipamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipamentosSlugRoute = EquipamentosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EquipamentosRoute,
} as any)
const EmpresasSlugRoute = EmpresasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EmpresasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/empresas': typeof EmpresasRouteWithChildren
  '/equipamentos': typeof EquipamentosRouteWithChildren
  '/empresas/$slug': typeof EmpresasSlugRoute
  '/equipamentos/$slug': typeof EquipamentosSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/empresas': typeof EmpresasRouteWithChildren
  '/equipamentos': typeof EquipamentosRouteWithChildren
  '/empresas/$slug': typeof EmpresasSlugRoute
  '/equipamentos/$slug': typeof EquipamentosSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/empresas': typeof EmpresasRouteWithChildren
  '/equipamentos': typeof EquipamentosRouteWithChildren
  '/empresas/$slug': typeof EmpresasSlugRoute
  '/equipamentos/$slug': typeof EquipamentosSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/empresas'
    | '/equipamentos'
    | '/empresas/$slug'
    | '/equipamentos/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/empresas'
    | '/equipamentos'
    | '/empresas/$slug'
    | '/equipamentos/$slug'
  id:
    | '__root__'
    | '/'
    | '/empresas'
    | '/equipamentos'
    | '/empresas/$slug'
    | '/equipamentos/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmpresasRoute: typeof EmpresasRouteWithChildren
  EquipamentosRoute: typeof EquipamentosRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/equipamentos': {
      id: '/equipamentos'
      path: '/equipamentos'
      fullPath: '/equipamentos'
      preLoaderRoute: typeof EquipamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas': {
      id: '/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipamentos/$slug': {
      id: '/equipamentos/$slug'
      path: '/$slug'
      fullPath: '/equipamentos/$slug'
      preLoaderRoute: typeof EquipamentosSlugRouteImport
      parentRoute: typeof EquipamentosRoute
    }
    '/empresas/$slug': {
      id: '/empresas/$slug'
      path: '/$slug'
      fullPath: '/empresas/$slug'
      preLoaderRoute: typeof EmpresasSlugRouteImport
      parentRoute: typeof EmpresasRoute
    }
  }
}

interface EmpresasRouteChildren {
  EmpresasSlugRoute: typeof EmpresasSlugRoute
}

const EmpresasRouteChildren: EmpresasRouteChildren = {
  EmpresasSlugRoute: EmpresasSlugRoute,
}

const EmpresasRouteWithChildren = EmpresasRoute._addFileChildren(
  EmpresasRouteChildren,
)

interface EquipamentosRouteChildren {
  EquipamentosSlugRoute: typeof EquipamentosSlugRoute
}

const EquipamentosRouteChildren: EquipamentosRouteChildren = {
  EquipamentosSlugRoute: EquipamentosSlugRoute,
}

const EquipamentosRouteWithChildren = EquipamentosRoute._addFileChildren(
  EquipamentosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmpresasRoute: EmpresasRouteWithChildren,
  EquipamentosRoute: EquipamentosRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
